name: quicksight
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  go_router: ^14.6.0
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2
  http: ^1.2.2
  http_parser: ^4.0.1
  mime: ^2.0.0
  just_audio: ^0.9.39
  path_provider: ^2.1.5
  flutter_tts: ^4.2.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/logo/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/audio/
